#!/usr/bin/env bash

_watch() {
   inotifywait -m vendor/streams/*/resources/public -r -e modify,create,moved_to |
        while read path action file; do
            echo "${action}: ${path}'"
            php artisan vendor:publish --tag=public --force
        done
}

_link(){
    cd vendor/streams
    rm -rf core ui
    ln -s ../../packages/streams/core core
    ln -s ../../packages/streams/ui ui
}

_bootstrap(){
    git clone git@github.com:laravel-streams/streams-core packages/streams/core
    git clone git@github.com:laravel-streams/streams-ui packages/streams/ui
}

_switch-packages-feature(){
    _bootstrap
    WD=$PWD
    cd $WD/packages/streams/core
    git checkout feature/webpack-mix-root-based-bundling

    cd $WD/packages/streams/ui
    git checkout feature/webpack-mix-root-based-bundling
}


_$*
