#!/usr/bin/env bash

MYDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

_watch() {
   inotifywait -m vendor/streams/*/resources/public -r -e modify,create,moved_to |
        while read path action file; do
            echo "${action}: ${path}'"
            php artisan vendor:publish --tag=public --force
        done
}

_link(){
    cd $MYDIR/vendor/streams
    rm -rf core ui
    ln -s $MYDIR/packages/streams/core core
    ln -s $MYDIR/packages/streams/ui ui
}

_clone(){
    rm -rf $MYDIR/packages/streams/core
    rm -rf $MYDIR/packages/streams/ui
    git clone git@github.com:laravel-streams/streams-core $MYDIR/packages/streams/core
    git clone git@github.com:laravel-streams/streams-ui $MYDIR/packages/streams/ui
}

_switch-packages-feature(){
    cd $MYDIR/packages/streams/core
    git checkout feature/webpack-mix-root-based-bundling

    cd $MYDIR/packages/streams/ui
    git checkout feature/webpack-mix-root-based-bundling
}

_bootstrap(){
    _clone
    _switch-packages-feature
    _link
}

_$*
