#!/usr/bin/env bash

_watch() {
   inotifywait -m vendor/streams/*/resources/public -r -e modify,create,moved_to |
        while read path action file; do
            echo "${action}: ${path}'"
            php artisan vendor:publish --tag=public --force
        done
}



_$*
