module.exports = {
  purge: {
    enabled: false,
    content: [
      './resources/views/**/*.html',
      './docs/**/*.md',
      './resources/js/**/*.vue',
      './resources/js/**/*.js',
    ],
    options: {
      whitelist: [
        'bg-background',
        'bg-surface',
        'bg-accent',
        'bg-font',
        'bg-font-secondary',
        'text-background',
        'text-surface',
        'text-accent',
        'text-font',
        'text-font-secondary',
      ],
    }
  },

  theme: {
    colors: {
      background: "var(--color-background)",
      surface: "var(--color-surface)",
      accent: "var(--color-accent)",
      font: "var(--color-font)",
      "font-secondary": "var(--color-font-secondary)", 
    },
    fontFamily: {
      sans: "var(--font-body)",
      body: "var(--font-body)",
      display: "var(--font-display)",
      mono: "var(--font-mono)",
    },
    fontSize: {
      base: "var(--font-size-base)",
      h1: "var(--font-size-h1)",
      h2: "var(--font-size-h2)",
      h3: "var(--font-size-h3)",
      h4: "var(--font-size-h4)",
    },
    fontWeight: {
      normal: "var(--font-weight-normal)",
      semi: "var(--font-weight-semi)",
      bold: "var(--font-weight-bold)",
    },
    lineHeight: {
      none: '1',
      tight: '1.15',
      snug: '1.25',
      normal: '1.5',
      relaxed: '1.625',
    },
    zIndex: {
      auto: 'auto',
      '0': '0',
      '10': '10',
      '20': '20',
      '30': '30',
      '40': '40',
      '50': '50',
      '998': '998',
      '999': '999',
    },
    spacing: {
      px: '1px',
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
    },
    extend: {},
  },
  variants: {},
  plugins: [],
}
